-- ============================================
-- Database Setup for Event Registrations
-- ============================================
-- Linguistic Tornado 2025 Registrations Table Only
-- No RLS policies - direct access allowed
-- ============================================

-- Table: Linguistic Tornado 2025 Registrations
CREATE TABLE IF NOT EXISTS linguistic_tornado_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name VARCHAR(255) NOT NULL,
    grade VARCHAR(20) NOT NULL,
    school_name VARCHAR(255),
    parent_name VARCHAR(255) NOT NULL,
    contact_number VARCHAR(20) NOT NULL,
    email VARCHAR(255),
    city VARCHAR(100),
    registration_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_linguistic_email ON linguistic_tornado_registrations(email);
CREATE INDEX IF NOT EXISTS idx_linguistic_contact ON linguistic_tornado_registrations(contact_number);
CREATE INDEX IF NOT EXISTS idx_linguistic_registration_date ON linguistic_tornado_registrations(registration_date);
CREATE INDEX IF NOT EXISTS idx_linguistic_grade ON linguistic_tornado_registrations(grade);

-- Add comments for documentation
COMMENT ON TABLE linguistic_tornado_registrations IS 'Registrations for Linguistic Tornado 2025 event';
COMMENT ON COLUMN linguistic_tornado_registrations.student_name IS 'Name of the student attending';
COMMENT ON COLUMN linguistic_tornado_registrations.grade IS 'Grade level (1-5)';
COMMENT ON COLUMN linguistic_tornado_registrations.parent_name IS 'Parent or guardian name';
COMMENT ON COLUMN linguistic_tornado_registrations.contact_number IS 'Parent contact number';

-- ============================================
-- View to see Linguistic Tornado registrations
-- ============================================
CREATE OR REPLACE VIEW linguistic_registrations_view AS
SELECT 
    'Linguistic Tornado 2025' as event_name,
    student_name as participant_name,
    grade,
    school_name,
    parent_name,
    contact_number,
    email,
    city,
    registration_date
FROM linguistic_tornado_registrations;

COMMENT ON VIEW linguistic_registrations_view IS 'View of Linguistic Tornado 2025 registrations';

-- ============================================
-- Sample Queries (for reference)
-- ============================================

-- Get all Linguistic Tornado registrations
-- SELECT * FROM linguistic_tornado_registrations ORDER BY registration_date DESC;

-- Get registrations by grade
-- SELECT grade, COUNT(*) as count 
-- FROM linguistic_tornado_registrations 
-- GROUP BY grade ORDER BY grade;

-- Get registrations by school
-- SELECT school_name, COUNT(*) as count 
-- FROM linguistic_tornado_registrations 
-- WHERE school_name IS NOT NULL
-- GROUP BY school_name ORDER BY count DESC;

-- Get recent registrations (last 7 days)
-- SELECT * FROM linguistic_tornado_registrations 
-- WHERE registration_date >= NOW() - INTERVAL '7 days'
-- ORDER BY registration_date DESC;

-- Get registrations from view
-- SELECT * FROM linguistic_registrations_view ORDER BY registration_date DESC;

-- ============================================
-- Setup Complete
-- ============================================
