-- ============================================
-- NxtZen Winter 2025 Registration Table
-- No RLS policies - direct access allowed
-- ============================================

CREATE TABLE IF NOT EXISTS nxtzenwinter2025_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name VARCHAR(255) NOT NULL,
    grade VARCHAR(20) NOT NULL,     -- e.g. "1-2", "3-5", "6-8", "9-10", "11-12"
    school_name VARCHAR(255),
    parent_name VARCHAR(255) NOT NULL,
    contact_number VARCHAR(20) NOT NULL,     -- store as text to avoid formatting issues
    email VARCHAR(255),
    city VARCHAR(100),
    registration_date TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Optional helpful indexes
CREATE INDEX IF NOT EXISTS idx_nxtzenwinter2025_grade
    ON nxtzenwinter2025_registrations (grade);

CREATE INDEX IF NOT EXISTS idx_nxtzenwinter2025_contact
    ON nxtzenwinter2025_registrations (contact_number);

CREATE INDEX IF NOT EXISTS idx_nxtzenwinter2025_created
    ON nxtzenwinter2025_registrations (registration_date);

-- Add comments for documentation
COMMENT ON TABLE nxtzenwinter2025_registrations IS 'Registrations for NxtZen Winter 2025 event';
COMMENT ON COLUMN nxtzenwinter2025_registrations.student_name IS 'Name of the student attending';
COMMENT ON COLUMN nxtzenwinter2025_registrations.grade IS 'Grade level (1-2, 3-5, 6-8, 9-10, 11-12)';
COMMENT ON COLUMN nxtzenwinter2025_registrations.parent_name IS 'Parent or guardian name';
COMMENT ON COLUMN nxtzenwinter2025_registrations.contact_number IS 'Parent contact number';

-- ============================================
-- Sample Queries (for reference)
-- ============================================

-- Get all NxtZen Winter 2025 registrations
-- SELECT * FROM nxtzenwinter2025_registrations ORDER BY registration_date DESC;

-- Get registrations by grade
-- SELECT grade, COUNT(*) as count 
-- FROM nxtzenwinter2025_registrations 
-- GROUP BY grade ORDER BY grade;

-- Get registrations by school
-- SELECT school_name, COUNT(*) as count 
-- FROM nxtzenwinter2025_registrations 
-- WHERE school_name IS NOT NULL
-- GROUP BY school_name ORDER BY count DESC;

-- Get recent registrations (last 7 days)
-- SELECT * FROM nxtzenwinter2025_registrations 
-- WHERE registration_date >= NOW() - INTERVAL '7 days'
-- ORDER BY registration_date DESC;

-- ============================================
-- Setup Complete
-- ============================================
