-- Create table for Math Day 2025 Project Uploads
create table if not exists math_project_uploads (
  id bigint generated by default as identity primary key,
  registration_id text not null,
  email_id text not null,
  full_name text not null,
  competition_course text,
  file_path text not null,
  file_type text,
  uploaded_at timestamp with time zone default timezone('utc'::text, now()) not null,
  status text default 'uploaded' check (status in ('uploaded', 'reuploaded', 'verified'))
);

-- Note: RLS policies are skipped as per request ("rls policies lam venam")
-- The code assumes 'math_lead_registrations' exists for the foreign key lookup, 
-- but we are not enforcing a hard foreign key constraint here to keep it simple as requested,
-- though strictly referencing it would be better for data integrity. 
-- We'll just index the email for faster lookups if needed.

create index if not exists idx_math_uploads_email on math_project_uploads(email_id);
create index if not exists idx_math_uploads_reg_id on math_project_uploads(registration_id);
